package msgModel;

import static io.netty.buffer.Unpooled.buffer;

import io.netty.buffer.ByteBuf;

public class BarrierReply {
	
	/*
	 * This function creates a Barrier Reply message in response to the Barrier Request message received by the controller
	 * @param - Barrier Request message sent by controller
	 * @return - Barrier Reply message generated by the Agent
	 */
	
	public ByteBuf create(ByteBuf msg){

		ByteBuf b = buffer(8);

		b.writeByte(4); // OF version
		b.writeByte(21); // msg Type
		b.writeShort(8); // length
		b.writeInt(msg.getInt(4)); //TxID
		
		msg.release();
		
		return b;
	}
}