package msgModel;

import static io.netty.buffer.Unpooled.buffer;

import io.netty.buffer.ByteBuf;

public class RoleReply {
	
	/*
	 * This function creates a Role Reply message in response to the Role Request message received by the controller
	 * @param - Role Request message sent by controller
	 * @return - Role Reply message generated by the Agent
	 */
	
	public ByteBuf create(ByteBuf msg){

		ByteBuf b = buffer(24);

		b.writeByte(4); // OF version
		b.writeByte(25); // OF msg Type
		b.writeShort(24); // length
		b.writeInt(msg.getInt(4)); // TxID

		b.writeInt(msg.getInt(8)); // set controller role
		b.writeInt(0); // pad[4]
		b.writeLong(msg.getLong(16)); //generation Id

		msg.release();
		return b;
	}
}